name: 'action-renovate-checkbox'
description: 'Trigger Renovate with the Dependency Dashboard checkbox.'
inputs:
  dependency-dashboard-id:
    description: 'The issue ID of the Dependency Dashboard, add `"masterIssue": true` to your Renovate config first.'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
